arguments:
  user: "ocdkube24-oc"
  auth_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUyNC1vYyIsInJvbGUiOiJkYXRhc2NpZW50aXN0LG1sZSxwZSIsImRlcGxveSI6ZmFsc2UsImV4cCI6NDk1MjA0MjMwOSwiaWF0IjoxNzEyMDQyMzA5LCJpc3MiOiJEa3ViZSJ9.d09WLJEdWGgitJhKK2z2vuKn0a2Yq-eaN1CFJ73V_-ga-Ka_Va77cAvSAB6betFUmz5Qu66uKhKZXv7ptZ21MbHQCiNwPFPYZyh9bFJHPXPQGAlTyuhzce73sQjLyhxqJwegyOxgjHkBXeUdiXcE7pkEi_jVtf0fKkcpGoKWkZBQxRMRrYjfIG1XM10y1K9EMfaG-TtDEAskC6BiZktWFQAgQIgZzR4vasYSEGL9t5XYsbfce91GTerCqDs5XRzeIvpKpgBaG0n0VzvFNqwhjI8KmvvJDButQpdlGA0OuMUYB-FZO5Ix2LzhvsiKfkNTITGU31_DOYgBlbkQTHcgUQ"
  project_id: "ybuf72"
  tags: '["regression","testing"]'
