arguments:
  user: "ocdkube2"
  auth_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc0YmNkZjBmZWJmNDRiOGRhZGQxZWIyOGM2MjhkYWYxIn0.eyJ1c2VybmFtZSI6Im9jZGt1YmUyIiwicm9sZSI6ImRhdGFzY2llbnRpc3QsbWxlLHBlIiwiZGVwbG95IjpmYWxzZSwiZXhwIjo0OTQ4NTA5ODAwLCJpYXQiOjE3MDg1MDk4MDAsImlzcyI6IkRrdWJlIn0.XR0wCbjsJ2H561XWWsZZYQgAuMzzF-S07OgGFdduMFdBMHr2C4wvObq-mKLtlMerT-cqlR1H5vbOOkH-OorNGPJ_4X38hRDoqckbVrsFTuZ36vQ7pIZlUzET5TXB25eepmnFRI-dLcOCDctIcac6vXF7FiTgNFzn8h2HQJ6Rk23tIVuAT9NapOqZR84vz5LDAT70Y2XAjqj-ln5Nff9Rc4iCX5Z72ZkaRpZ5bDjS9-twrAFW-XwA7wKqsxnHrEinhWQH1_Pf13-IsuX0xzPtm9bBjcSfKXRf2rb65xObFqRVN_3OtvP-Gg7Ld-KY0_y1EZTXHQmQ_lQirOpaQPFGsw"
  project_id: "ui19z5"
  tags: '["project:ui19z5","testing","sbr"]'
